### ISSUE TITLE
[Discuss] Define the configuration format the agent should provide to the shipper

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-shipper#53]
An initial configuration file for the shipper has been defined at https://github.com/elastic/elastic-agent-shipper/blob/main/elastic-agent-shipper.yml, but it does not yet include all of the information required for the shipper to run.

We must define the subset of an agent policy that should be sent to each instance of a shipper process started by the agent. 

Relates to:
- https://github.com/elastic/elastic-agent-shipper/issues/13
- https://github.com/elastic/elastic-agent-shipper/issues/52
- https://github.com/elastic/elastic-agent/issues/220
- https://github.com/elastic/elastic-agent/issues/219

Consider a simple agent policy like https://gist.github.com/blakerouse/88c9e461c031fc089e0f8601b78b48de. Then each defined output will map to an instance of the shipper process that should be provided with:

- The contents of the `output` section for the started shipper.
- The contents of the `agent.monitoring` section to control shipper monitoring.
- For each input configured to use the the applicable shipper instance that defines a processor, the relevant sub-set of the input definition. The shipper needs at least the input ID, data stream identifiers, and processor configurations.

For the sample agent policy above, we could receive at least the following configuration almost verbatim from the agent policy.

```yml
outputs:
    type: elasticsearch
    hosts:
      - 'http://localhost:9200'
agent:
  monitoring:
    enabled: true
    use_output: default
    namespace: default
    logs: true
    metrics: true
inputs:
  - id: default-system-policy
    data_stream:
      namespace: default
    streams:
      - id: logfile-system.auth-default-system-policy
        data_stream:
          dataset: system.auth
          type: logs
        processors:
          - add_locale: null
      - id: logfile-system.syslog-default-system-policy
        data_stream:
          dataset: system.syslog
          type: logs
        processors:
          - add_locale: null
  - id: default-system-policy
    data_stream:
      namespace: default
    streams:
      - id: system/metrics-system.filesystem-default-system-policy
        data_stream:
          dataset: system.filesystem
          type: metrics
        processors:
          - drop_event.when.regexp:
              system.filesystem.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
      - id: system/metrics-system.fsstat-default-system-policy
        data_stream:
          dataset: system.fsstat
          type: metrics
        processors:
          - drop_event.when.regexp:
              system.fsstat.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
```

We need to decide if this is the complete set of information needed to run the shipper. We could for example include the IDs, names, and meta information of each input that would communicate with the shipper to allow us to enrich our logs and traces with that information.

**Comment by cmacknz** [comment]
CC @rdner as this will likely define how the shipper receives the processor list from the agent.

CC @fearful-symmetry since the configuration format should be finalized to complete https://github.com/elastic/elastic-agent-shipper/issues/13

**Comment by rdner** [comment]
In my [proposal document](https://docs.google.com/document/d/1fI6vBcxpxAhS4YtEhpveKR8y_irqPNqSOW2RTuRX8cc/edit) I had the following example:

```yaml
outputs:
  default:
    type: elasticsearch
    hosts:
      - 'http://localhost:9200'
inputs:
  - id: default-system-policy # unique for the entire policy
    use_output: default       # output is declared only on the input level
    processors:               # list of processors for the input level
      - add_locale: null
    data_stream:              # data stream parameters of the input level 
                              # (can be overridden by streams)
      namespace: default
      dataset: system.auth
      type: logs
    streams:                  # optional, some inputs don’t have streams
      - id: logfile-system.auth-default-system-policy
        data_stream:          # overrides the input level `data_stream`
          dataset: system.auth
          type: logs
        processors:           # additional processors to what declared 
                              # on the input level
          - add_locale: null
```

This is the bare minimum we would need in the shipper, it does not have to be exactly that but it's something we could start the discussion with.
