### ISSUE TITLE
[META][Feature] Enable filebeat and metricbeat to publish data to the shipper

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-shipper#8]
This is a feature meta issue (expected to have sub-issues) to allow filebeat and metricbeat to publish data to the shipper when run under Elastic agent. All other beats are out of scope.

An output for existing beats should be implemented that publishes to the shipper gRPC interface. When the shipper gRPC output is used, the beat output pipeline should be configured to be as simple as possible. Using a per beat disk queue with the shipper is forbidden. A memory queue may be used with the shipper output, but how it should be configured by users will require careful consideration. Ideally any necessary queue configuration can be made automatic. 

Removing processors from beats is out of scope for this issue. Processors will be removed in a later issue.

This feature is considered complete when at least the following criteria are satisfied:
- For both filebeat and metricbeat:
  - A test exists proving data ingested by the beat is published to the shipper.
  - A test exists proving there is no data loss when the shipper process restarts while the beat is publishing.
  - A test exists proving there is no data loss when the shipper backpressures the beat (because the shipper queue is full for example).

The following set of tasks should be included in the initial issues at a minimum:
- Creating a beats output that that publishes to the shipper gRPC interface.
- Defining a standard configuration for using a beat with the shipper that the control plane can easily apply: processors disabled, queues disabled, etc.
- Creating an integration test suite for the beat and shipper interactions.

**Comment by rdner** [comment]
> Creating a beats output that that publishes to the shipper gRPC interface.

@cmacknz I'm a bit confused about this sentence.

When we talked 1 on 1, we agreed that during the very first iteration the gRPC server will be one of the output options along with Elasticsearch, File output, Kafka, etc.

Later at the team call I asked the same question to widen the discussion circle but then you answered something different about having a feature flag and switching some logic in the code.

I think we have some miscommunication about this.

I see 2 options how to approach this task:

## Option 1

We have it as a new experimental [output type](https://github.com/elastic/beats/blob/652b6911ad16751e15d9b2a567161371ce160db7/libbeat/outputs/output_reg.go#L58-L64) which we could configure like this:

```yaml
output:
  shipper:
    server: "localhost:50051" # The server address in the format of host:port
    tls: true # Connection uses TLS if true, else plain TC
    ca_file: "/home/cert" # The file containing the CA root cert file
    server_host_override: "x.test.example.com" # The server name used to verify the hostname returned by the TLS handshake
```

This can be achieved with the following steps:

1. We create a new package `shipper` in here https://github.com/elastic/beats/tree/main/libbeat/outputs (or perhaps in `elastic-agent-libs`)
2. We implement the [Client interface](https://github.com/elastic/beats/blob/652b6911ad16751e15d9b2a567161371ce160db7/libbeat/outputs/outputs.go#L29-L44)
3. We implement the new [shipper output type factory](https://github.com/elastic/beats/blob/652b6911ad16751e15d9b2a567161371ce160db7/libbeat/outputs/output_reg.go#L58-L64).
4. We use the existing [pipeline](https://github.com/elastic/beats/blob/main/libbeat/publisher/pipeline/pipeline.go) without any changes.

In this case, changes of the existing code are none or minimal and we can start working with the new setup, debug and perform tests. The new output type can be excluded from the documentation if needed. Later we can just replace the whole pipeline implementation when we feel the shipper is ready.

## Option 2

We have a feature flag to switch the [pipeline](https://github.com/elastic/beats/blob/main/libbeat/publisher/pipeline/pipeline.go) to a separate implementation that starts sending events to the shipper instead of configured outputs.

This will require us:

1. Refactor the current [pipeline implementation](https://github.com/elastic/beats/blob/main/libbeat/publisher/pipeline/pipeline.go) so it's an interface that can have 2 different implementations instead of a struct
2. Create a new configuration section support at the root level where we can configure a shipper, e.g.:
```yaml
shipper:
  server: "localhost:50051" # The server address in the format of host:port
  tls: true # Connection uses TLS if true, else plain TC
  ca_file: "/home/cert" # The file containing the CA root cert file
  server_host_override: "x.test.example.com" # The server name used to verify the hostname returned by the TLS handshake
```
3. If the configuration section exists, the pipeline implementation is switched to the `ShipperPipeline` and the beat's output configuration is ignored

The major drawback here is that we would need more time and to make a lot of changes to the existing code instead of just adding new that can affect stability. On the other hand, we would need to do that at some point too.
